### PR TITLE
release gnbsim image

### PR DESCRIPTION
**Pull request by thakurajayL**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
The chart version for the `sdcore-helm-charts` should be increased to `1.0.11` in [here](https://github.com/omec-project/sdcore-helm-charts/pull/45/files#diff-5912a09463eaf2fc3ee57e43b57bd78848b2251a38ffa86d8a4444c16bf0b65bR13)

**Comment by thakurajayL** [comment]
> The chart version for the `sdcore-helm-charts` should be increased to `1.0.11` in [here](https://github.com/omec-project/sdcore-helm-charts/pull/45/files#diff-5912a09463eaf2fc3ee57e43b57bd78848b2251a38ffa86d8a4444c16bf0b65bR13)

Is it possible to detect these issues in CI checks?

**Comment by gab-arrobo** [comment]
> > The chart version for the `sdcore-helm-charts` should be increased to `1.0.11` in [here](https://github.com/omec-project/sdcore-helm-charts/pull/45/files#diff-5912a09463eaf2fc3ee57e43b57bd78848b2251a38ffa86d8a4444c16bf0b65bR13)
> 
> Is it possible to detect these issues in CI checks?

I think it is doable. However, I/we need to spend some time adding that capability/check.

**Review by gab-arrobo — APPROVED** [review]
+1

**Pull request merged**
